version: '3'

services:
    postgres14:
        container_name: Postgres14
        
        image: postgres:14
        restart: unless-stopped
        
        volumes:
            - type: bind
              source: /home/postgresql/data
              target: /var/lib/postgresql/data

        environment:
            TZ: "Asia/Shanghai"
            POSTGRES_PASSWORD: "mysecretpassword"
        
        ports:
            - '5432:5432'

    redis7:
        container_name: Redis7
        
        image: redis:7
        restart: unless-stopped
        
        environment:
            TZ: "Asia/Shanghai"
        
        ports:
          - '6379:6379'

    meilisearch:
        container_name: Meilisearch
        
        image: getmeili/meilisearch
        restart: unless-stopped
        
        environment:
            TZ: "Asia/Shanghai"
            MEILI_MASTER_KEY: masterkey
        
        ports:
            - "7700:7700"


    kitsu:
        container_name: Kitsu
      
        image: kitsu
        restart: unless-stopped
        
        depends_on:
            - postgres14
            - redis7
            - meilisearch

        environment:
            TZ: "Asia/Shanghai"
            KV_HOST: redis7
            KV_PORT: 6379

            DB_HOST: postgres14
            DB_PORT: 5432
            DB_USERNAME: kitsu_db_user
            DB_PASSWORD: "mysecretpassword"
            DB_DATABASE: kitsu_db
            DB_POOL_SIZE: 30
            DB_MAX_OVERFLOW: 60

            INDEXER_KEY: masterkey
            INDEXER_HOST: meilisearch
            INDEXER_POER: 7700

        ports:
          - '5000:5000'
          - '5001:5001'
          - '80:8080'

